# Generated by Django 6.1 on 2026-08-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='men',
            name='is_published',
        ),
    ]
